"""Entra ID OAuth2 authorization-code flow (entra_oidc mode).

MSAL's confidential client runs the code exchange server-side. The short-lived
flow state (state + PKCE verifier, generated by MSAL) rides in its own signed
cookie between /login and /callback so the backend stays stateless.

Roles come from the app registration's App Roles assigned to the user/groups
in Entra — the same `roles` claim EasyAuth mode reads — so the tower mapping
in towers.registry works identically across auth modes.
"""

from __future__ import annotations

import logging

import msal
from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer

from ...config import settings
from ..towers.registry import towers_for_roles
from .schemas import CurrentUser

logger = logging.getLogger(__name__)

FLOW_COOKIE = "jbs_auth_flow"
FLOW_MAX_AGE = 600  # login must complete within 10 minutes
SCOPES: list[str] = []  # openid/profile are implied; we only need the id_token


def _client() -> msal.ConfidentialClientApplication:
    if not (settings.entra_tenant_id and settings.entra_client_id):
        raise RuntimeError(
            "ENTRA_TENANT_ID and ENTRA_CLIENT_ID must be set in entra_oidc mode"
        )
    return msal.ConfidentialClientApplication(
        client_id=settings.entra_client_id,
        client_credential=settings.entra_client_secret,
        authority=settings.entra_authority,
    )


def _flow_serializer() -> URLSafeTimedSerializer:
    return URLSafeTimedSerializer(settings.session_secret, salt="jbs-auth-flow")


def build_auth_flow(redirect_after: str) -> tuple[str, str]:
    """Start the code flow. Returns (microsoft_auth_url, signed_flow_state)."""
    flow = _client().initiate_auth_code_flow(
        scopes=SCOPES,
        redirect_uri=settings.entra_redirect_uri,
    )
    flow["redirect_after"] = redirect_after
    return flow["auth_uri"], _flow_serializer().dumps(flow)


def complete_auth_flow(signed_flow: str, callback_params: dict) -> tuple[CurrentUser, str]:
    """Finish the code flow. Returns (user, redirect_after). Raises ValueError."""
    try:
        flow = _flow_serializer().loads(signed_flow, max_age=FLOW_MAX_AGE)
    except (SignatureExpired, BadSignature) as exc:
        raise ValueError("Login flow expired or was tampered with") from exc

    redirect_after = flow.pop("redirect_after", "/")
    result = _client().acquire_token_by_auth_code_flow(flow, callback_params)
    if "error" in result:
        logger.warning("Entra token exchange failed: %s", result.get("error_description"))
        raise ValueError(result.get("error_description", result["error"]))

    claims = result.get("id_token_claims", {})
    email = claims.get("preferred_username") or claims.get("email") or ""
    roles = claims.get("roles", []) or []
    user = CurrentUser(
        id=claims.get("oid") or claims.get("sub") or email,
        email=email,
        name=claims.get("name") or email,
        roles=roles,
        towers=[t.id for t in towers_for_roles(roles)],
    )
    return user, redirect_after


def logout_url(post_logout_redirect: str) -> str:
    return (
        f"{settings.entra_authority}/oauth2/v2.0/logout"
        f"?post_logout_redirect_uri={post_logout_redirect}"
    )
